config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/create_lobby', to: 'game#create_lobby'
  get '/create_page', to: 'game#create_page'
  post '/join_lobby', to: 'game#join_lobby'
  get '/join_page', to: 'game#join_page'
  get '/play', to: 'game#play'
  get '/cancel', to: 'game#cancel'
  post '/exit', to: 'game#exit'
  post '/win', to: 'game#win'
  get '/get_win', to: 'game#get_win'
  get '/main', to: 'game#main'

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token

  get "password_rest", to: "passwords#new"

  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end

  get '/edit_labyrinth', to: 'game#edit_labyrinth'
  post '/save_labyrinth', to: 'game#save_labyrinth'
  get '/reset_labyrinth', to: 'game#reset_labyrinth'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#omniauth'

  get '/set_other_labyrinth', to: 'game#set_other_labyrinth'

  get '/move_up', to: 'game#move_up'
  get '/move_right', to: 'game#move_right'
  get '/move_down', to: 'game#move_down'
  get '/move_left', to: 'game#move_left'

  get '/update_labyrinth', to: 'game#update_labyrinth'
  get '/get_turn', to: 'game#get_turn'
  post '/set_turn', to: 'game#set_turn'
end

app/models/user.rb
class User < ApplicationRecord
  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes

  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  MAILER_FROM_EMAIL = ENV['EMAIL_USERNAME']

  has_secure_password

  attr_accessor :current_password

  has_many :active_sessions, dependent: :destroy
  has_one :game, dependent: :destroy
  has_one :labyrinth, dependent: :destroy

  before_save :downcase_email
  before_save :downcase_unconfirmed_email

  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true
  validates :unconfirmed_email, format: {with: URI::MailTo::EMAIL_REGEXP, allow_blank: true}

  def confirm!
    if unconfirmed_or_reconfirming?
      if unconfirmed_email.present?
        return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
      end
      update_columns(confirmed_at: Time.current)
    else
      false
    end
  end

  def confirmed?
    confirmed_at.present?
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def unconfirmed?
    !confirmed?
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, "One or more password arguments are required" if passwords.empty?
    raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
    if (record = find_by(identifiers))
      record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
    else
      new(passwords)
      nil
    end
  end

  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      user.save
    else
      user = User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = SecureRandom.hex(15)
      end
    end
    user
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?
    self.unconfirmed_email = unconfirmed_email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy, :update]
  before_action :redirect_if_authenticated, only: [:create, :new]

  def create
    @user = User.new(create_user_params)
    if @user.save
      @user.send_confirmation_email!
      redirect_to root_path, notice: "Please check your email for confirmation instructions."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: "Your account has been deleted."
  end

  def edit
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
  end

  def update
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
    if @user.authenticate(params[:user][:current_password])
      if @user.update(update_user_params)
        if params[:user][:unconfirmed_email].present?
          @user.send_confirmation_email!
          redirect_to root_path, notice: "Check your email for confirmation instructions."
        else
          redirect_to root_path, notice: "Account updated."
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:error] = "Incorrect password"
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @user = User.new
  end

  private

  def create_user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation, :unconfirmed_email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render("layouts/navbar") %>
<%= stylesheet_link_tag "edit_form" %>
<div class="edit_page">
  <div class="edit_form">
    <%= form_with model: @user, url: account_path, method: :put do |form| %>
      <%= render partial: "shared/form_errors", locals: { object: form.object } %>
      <div>
        <%= form.label :email, "Current Email" %>
        <%= form.email_field :email, disabled: true %>
      </div>
      <div>
        <%= form.label :unconfirmed_email, "New Email" %>
        <%= form.text_field :unconfirmed_email, placeholder: "Enter New Email" %>
      </div>
      <div>
        <%= form.label :password, "New Password (leave blank if you don't want to change it)" %>
        <%= form.password_field :password, placeholder: "Enter New Password" %>
      </div>
      <div>
        <%= form.label :password_confirmation, "New Password Confirmation" %>
        <%= form.password_field :password_confirmation, placeholder: "Repeat New Password" %>
      </div>
      <hr/>
      <div>
        <%= form.label :current_password, "Current Password (we need your current password to confirm your changes)" %>
        <%= form.password_field :current_password, required: true, placeholder: "Enter Password" %>
      </div>
      <%= form.submit "Update Account" %>
    <% end %>

    <h2>Current Logins</h2>
    <% if @active_sessions.any? %>
      <%= button_to "Log out of all other sessions", destroy_all_active_sessions_path, method: :delete %>
      <table>
        <thead>
        <tr>
          <th>User Agent</th>
          <th>IP Address</th>
          <th>Signed In At</th>
          <th>Sign Out</th>
        </tr>
        </thead>
        <tbody>
        <%= render @active_sessions %>
        </tbody>
      </table>
    <% end %>

    <div>
      &nbsp
      <%= button_to "Delete account", '/account', method: :delete %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render("layouts/navbar") %>
<%= stylesheet_link_tag "form" %>
<div class="page">
  <div class="form">
    <h1>Register</h1>
    <p>Please fill in this form to create an account.</p>
    <%= form_with model: @user, url: sign_up_path do |form| %>
      <%= render partial: "shared/form_errors", locals: { object: form.object } %>
      <div>
        <%= form.label :email %>
        <%= form.email_field :email, required: true, placeholder: "Enter Email" %>
      </div>
      <div>
        <%= form.label :password %>
        <%= form.password_field :password, required: true, placeholder: "Enter Password" %>
      </div>
      <div>
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, required: true, placeholder: "Repeat Password" %>
      </div>
      <%= form.submit "Sign Up" %>
      <div>
        <%= link_to "Log in with Google", '/auth/google_oauth2', method: :post  %>
      </div>
      <p>Already have an account? <a href="/login">Login</a>.</p>
    <% end %>
  </div>
</div>